# Generated by Django 5.2 on 2025-04-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestBuy_bot', '0003_remove_products_category_alter_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
