# Generated by Django 5.2 on 2025-05-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestBuy_bot', '0006_badpassword_alter_product_category_additionalmarket_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
