# Generated by Django 5.2 on 2025-05-06 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestBuy_bot', '0007_rename_user_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user_name',
        ),
    ]
