# Generated by Django 5.2 on 2025-05-08 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestBuy_bot', '0008_rename_username_user_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
