# Generated by Django 5.2 on 2025-05-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestBuy_bot', '0010_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
