# Generated by Django 5.2 on 2025-05-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BestBuy_bot', '0011_remove_user_id_alter_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='working_hours_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='working_hours_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
