# Generated by Django 5.2 on 2025-05-28 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BestBuy_bot', '0012_alter_market_working_hours_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='id',
        ),
    ]
