# Generated by Django 4.2.23 on 2025-06-19 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bestbuy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.JSONField()),
                ('about_company', models.TextField()),
                ('about_delivery', models.TextField()),
                ('announcement', models.TextField()),
                ('welcome_message', models.TextField()),
                ('welcome_video', models.FileField(blank=True, null=True, upload_to='welcome_videos/')),
                ('require_address', models.BooleanField(default=False)),
                ('require_registration', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='bestbuy_app.market')),
            ],
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=255, unique=True)),
                ('bot_name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('settings', models.JSONField(default=dict)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestbuy_app.market')),
            ],
        ),
    ]
