# Generated by Django 4.2.23 on 2025-06-19 10:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramBotConfig',
        ),
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Telegram Bot', 'verbose_name_plural': 'Telegram Bots'},
        ),
        migrations.AddField(
            model_name='bot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bot',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
