# Generated by Django 5.2 on 2025-06-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbuy_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
