# Generated by Django 4.2.23 on 2025-06-20 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestbuy_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BotConfiguration',
        ),
    ]
