# Generated by Django 5.2 on 2025-06-18 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbuy_app', '0002_deliverydepartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variations',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='variations',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='bestbuy_app.product'),
        ),
    ]
