# Generated by Django 5.2 on 2025-06-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbuy_app', '0003_remove_variations_product_id_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
