# Generated by Django 5.2 on 2025-06-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbuy_app', '0004_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
