# Generated by Django 5.2 on 2025-06-23 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestbuy_app', '0005_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='markets_owned', to='bestbuy_app.user'),
        ),
    ]
